# Generated by Django 4.2.3 on 2023-09-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение/превью'),
        ),
    ]
